# Create sample sets
A = {10, 20, 30, 40}
B = {30, 40, 50, 60}
print("Set A:", A)
print("Set B:", B)
# (a) add()
A.add(99)
print("\nAfter add(99) to Set A:", A)
# (b) update()
A.update([100, 200])
print("After update([100, 200]) to Set A:", A)
# (c) copy()
C = A.copy()
print("Copied set (Set C):", C)
# (d) pop()
A.pop()
print(f"After pop() from Set A: {A}")
# (e) remove()
A.remove(10) 
print("After remove(10) from Set A:", A)
# (f) discard()
A.discard(999) # 999 is not in the set, but no error is raised
print("After discard(999) from Set A:", A)
# (h) union()
print("Union of Set B and Set C:", B.union(C))
# (i) intersection()
print("Intersection of Set B and Set C:", B.intersection(C))
# (j) difference()
print("Difference (Set C - Set B):", C.difference(B))
# (g) clear()
A.clear()
print("After clear() on Set A:", A)