# (a) dict()
D = dict(name="Rafia", age=20, type="Student", course="BCA")
print("Original Dictionary:", D)
# (b) len()
print("Length of dictionary:", len(D))
# (d) get()
print("Get 'age':", D.get("age"))
# (g) keys(), (h) values(), (i) items()
print("Keys:", D.keys())
print("Values:", D.values())
print("Items:", D.items())
# (j) copy()
CD = D.copy()
print("Copied Dictionary:", CD)
# (k) update()
D.update({"Hobby": "Reading","name": "Rafia Khan"})
print("After update():", D)
# (e) pop()
popped_val = D.pop("Hobby")
print(f"After pop('Hobby') - Popped Value: {popped_val}")
# (f) popitem()
popped_item = D.popitem()
print(f"After popitem() - Popped Item: {popped_item}")
# (c) clear()
D.clear()
print("After clear():", D)